config/routes.rb
Rails.application.routes.draw do

  devise_for :users,:controllers => {
    :registrations => "registrations"
  }
  # get 'hello_world', to: 'hello_world#index'

  resources :items
  get 'cart', to: 'items#index'
  get 'inventario', to: 'items#index'
  get 'get_orders_refunded', to: 'orders#get_orders_refunded'
  get 'get_orders_searched', to: 'orders#get_orders_searched'
  get 'get_category_brand', to: 'items#get_category_brand'
  get 'get_items', to: 'items#get_items'
  get 'get_item_orders_refunded', to: 'item_orders#get_item_orders_refunded'


  resources :orders do
    resources :item_orders, only:[:edit, :update]
    resources :custom_items, only:[:edit, :update]
    resources :refund_orders, except:[:destroy] do
      resources :refund_items, except:[:destroy]
    end
  end

  root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :item_orders , :dependent => :destroy
  has_many :custom_items, :dependent => :destroy
  has_many :refund_orders, :dependent => :destroy

  has_many :items, through: :item_orders
  has_many :refund_items, through: :refund_orders

  validates_associated :refund_orders, :item_orders, :custom_items

  accepts_nested_attributes_for :item_orders
  enum order_type: [:sale, :buy, :void]

  scope :get_orders, -> (start_date, end_date) {where(["created_at >= ? AND created_at <= ?", start_date, end_date])}
  scope :get_orders_searched, -> (query) {where(["LOWER(name) LIKE ? OR CAST(id AS VARCHAR) LIKE ?", "%#{query}%", "%#{query}%"])}


  def calc_subtotal_refunded
    p "+++++++++++++++++++++++++++++++"
    p self.item_orders
    subtotal_item_orders = self.item_orders.reduce(0) { |st, item_order| st + item_order.subtotal_refunded }
    subtotal_custom_items = self.custom_items.reduce(0) { |st, custom_item| st + custom_item.subtotal_refunded }
    subtotal = subtotal_item_orders + subtotal_custom_items
    sprintf( '%.2f', subtotal )
  end

  def calc_taxes_refunded
    taxes = self.taxes == 0 ? 0 : self.subtotal_refunded * 0.115
    sprintf( '%.2f', taxes )
  end



  def calc_total_refunded
    sprintf('%.2f', self.subtotal_refunded + self.taxes_refunded )
  end

  def update_subtotal_refunded
    return self if self.update(subtotal_refunded: self.calc_subtotal_refunded)
  end

  def update_taxes_refunded
    return self if self.update(taxes_refunded: self.calc_taxes_refunded)
  end

  def update_total_refunded
    return self if self.update(total_refunded: self.calc_total_refunded)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
layout 'orders'
protect_from_forgery :except => [:create]

  def index
  end

  def show
    @order = Order.find(params[:id])
    p '++++++++++++++++ Order ++++++++++++++++++'
    p @order
    refund_orders = @order.refund_orders
    @cart = @order.item_orders
    @cart_item_orders = @cart.map {|cart_item| Item.find(cart_item.item_id) }
    @cart_custom_items = @order.custom_items.map {|cart_item| CustomItem.find(cart_item.id) }
    @subtotal_final = @order.subtotal - refund_orders.reduce(0) { |sum, ro| sum + ro.subtotal_refunded }
    @taxes_final = @order.taxes -  refund_orders.reduce(0) { |sum, ro| sum + ro.taxes_refunded }
    @total_final = @order.total - refund_orders.reduce(0) { |sum, ro| sum + ro.total_refunded }
    p @cart_custom_items
    respond_to do |format|
      format.html
      format.json {
        render json: {
          order: @order,
          cart: @cart,
          cart_items: @cart_items
        }
      }
    end
  end

  def edit
    @order = Order.find(params[:id])
    @cart = @order.item_orders
    @cart_item_orders = @cart.map {|cart_item| Item.find(cart_item.item_id) }
    @cart_custom_items = @order.custom_items.map {|cart_item| CustomItem.find(cart_item.id) }
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_payment_params)
      render :json => { order: @order , url: url_for(order_path(@order))}
    else
      render :json => { }, :status => 500
    end
  end

  def create
    p '================================'
    p params
    order = params[:order]
    cart_items = order[:itemOrders][:cartItems]
    cart_total = order[:itemOrders][:cartTotal]
    order_errors = []
    order_params = {
      order_type: order[:orderType],
      subtotal: cart_total[:subtotal],
      taxes: cart_total[:taxes],
      total: cart_total[:total],
      tax_free: order[:taxFree],
      cash_payed: order[:cashPayed],
      credit_card_payed: order[:creditCardPayed],
      debit_payed: order[:debitPayed],
      check_payed: order[:checkPayed],
      name: order[:orderName],
      telephone: order[:orderPhone]
    }
    @order = Order.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        item_id = cart_item[:item][:id]
        item = Item.find(item_id) if item_id < 9999
        if item
          @item_order = @order.item_orders.new(
            item_id: cart_item[:item][:id],
            order_id: @order[:id],
            quantity: cart_item[:quantity],
            price_given: cart_item[:priceGiven],
            subtotal: cart_item[:subtotal]
          )
          if @item_order.save
            new_quantity = item[:inventory] - cart_item[:quantity]
            item.update( inventory: new_quantity )
          else
            order_errors.push("Item order was not saved")
          end # end of item_order.save
        else
          @custom_items = @order.custom_items.new(
            quantity: cart_item[:quantity],
            price_given: cart_item[:priceGiven],
            subtotal: cart_item[:subtotal],
            name: cart_item[:item][:name]
          )
          if @custom_items.save

          else
            order_errors.push("Custom item was not saved")
          end
        end #end of if and else item
      end # end of cart_items.each
      return render :json => { order_id: @order.id , order_errors: order_errors}
    else
      render :json => { }, :status => 500
    end
  end

  def destroy
      @order = Order.find(params[:id])

      @order.item_orders.each do |item_order|

        if item_order.quantity_refunded < item_order.quantity
          quantity_difference = item_order.quantity - item_order.quantity_refunded
          p 'item_id=========================='
          quant_refunded = item_order.refund_items.reduce(0) {|total, ri| total += ri.quantity_refunded}
          item_order.item.update_inventory(item_order.item.inventory + quantity_difference - quant_refunded)
        end
      end
      @order.destroy
      redirect_to orders_path
  end

  def get_orders_refunded
    start_date = params[:startDate]
    if start_date != 'undefined'
      start_date = Date.parse(start_date).beginning_of_day
      end_date = DateTime.parse(params[:endDate]).end_of_day
      refund_orders = RefundOrder.get_refund_orders(start_date, end_date)
      orders = Order.get_orders(start_date, end_date).map{|o| o.as_json.merge!(refund: o.refund_orders.reduce(0){|sum, ro| sum += ro.total_refunded})}
    end


    refund_orders = refund_orders.distinct_orders.map{|val|
      order = Order.find(val.order_id)
      total_ref = order.refund_orders.reduce(0){ |sum, ro|
        sum + ro.subtotal_refunded + ro.taxes_refunded
      }
      order.as_json.merge!(total_ref: total_ref )
    }
    respond_to do |format|
    format.html
    format.json {
      render json: {
        refunded_orders: refund_orders,
        orders: orders
        }
      }
    end
  end

  def get_orders_searched
    query = params[:query].downcase
    orders = Order.get_orders_searched(query)
    respond_to do |format|
    format.html
    format.json {
      render json: {
        orders: orders
        }
      }
    end
  end

  private

  def order_payment_params
    params.require(:order).permit(:cash_payed, :credit_card_payed, :check_payed, :debit_payed)
  end

  def order_params
    params.require(:order)
      .permit(
        :order_type,
        :subtotal,
        :taxes,
        :total,
        :tax_free,
        :cash_payed,
        :credit_card_payed,
        :debit_payed,
        :check_payed,
        :name,
        :telephone
      )
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def display_price(number)
    number_with_precision(number, :precision => 2, :delimiter => ',' )
  end

  def display_refund(item, column)
    item_class = item.class
    item = item_class.find(item.id)
    item.refund_items.reduce(0) {|sum, item| sum + item[column]}
  end
end

app/views/orders/_order_details.html.erb
<table>
  <tbody>
    <tr class="order-th">
      <th>Marca</th>
      <th>Nombre</th>
      <th>Color</th>
      <th>Tamaño</th>
      <th>Grosor</th>
      <th>Precio Dado</th>
      <th>Cantidad Original</th>
      <th>Total Parcial Original</th>
      <th>Cantidad Reembolsada</th>
      <th>Subtotal De Reembolso</th>

      <!-- <th>Inventario</th> -->
    </tr>
    <% @cart_item_orders.each_with_index do |cart_item, ind| %>
        <tr  id= "<%= "cart-item-#{cart_item.id}" %>">
          <td><%= cart_item.brand %></td>
          <td><%= cart_item.name %></td>
          <td><%= cart_item.color %></td>
          <td><%= cart_item.size %></td>
          <td><%= cart_item.thickness %></td>
          <td>$<%= display_price(@cart[ind].price_given) %></td>
          <td id="<%= "quantity-#{cart_item.id}" %>"><%= @cart[ind].quantity %></td>
          <td>$<%= display_price(@cart[ind].subtotal) %></td>
          <td><%= display_refund(@cart[ind], 'quantity_refunded') %></td>
          <td>-$<%= display_refund(@cart[ind], 'subtotal_refunded') %></td>

          <!-- <td><%#= cart_item.inventory %></td> -->
        </tr>
      <% end %>
      <% @cart_custom_items.each_with_index do |cart_item, ind| %>
          <tr  id= "<%= "cart-item-#{cart_item.id}" %>">
            <td></td>
            <td><%= cart_item.name %></td>
            <td></td>
            <td></td>
            <td></td>
            <td>$<%= display_price(cart_item.price_given) %></td>
            <td id="<%= "quantity-#{cart_item.id}" %>"><%= cart_item.quantity %></td>
            <td>$<%= display_price(cart_item.subtotal) %></td>
            <td><%= cart_item.quantity_refunded%></td>
            <td>-$<%= cart_item.subtotal_refunded%></td>

            <!-- <td><%#= cart_item.inventory %></td> -->
          </tr>
        <% end %>

        <tr>
           <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
        </tr>
        <tr>
          <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
          <td>Subtotal Final</td>
          <td>$ <%= number_with_precision(@subtotal_final, :precision => 2, :delimiter => ",") %> </td>
        </tr>
        <tr>
          <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
          <td>Taxes Final</td>
          <td>$ <%= number_with_precision(@taxes_final, :precision => 2, :delimiter => ",") %> </td>
        </tr>
        <tr>
          <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
          <td>Total Final</td>
          <td id='total'>$ <%= number_with_precision(@total_final, :precision => 2, :delimiter => ",") %> </td>
        </tr>

  </tbody>
</table>

app/views/orders/edit.html.erb
<h1><%= @order.id %></h1>

<%= react_component('UpdateOrderPayment', props: {order: @order}, prerender: false) %>

<%= render 'order_details'%>

app/views/orders/index.html.erb
<div class="print-order-report hide-for-print">
 <h3><a href="#" onclick="window.print();return false;">Imprimir Página</a></h3>
</div>
  <%= react_component('Orders', props: {}, prerender: false) %>

app/views/orders/show.html.erb
<%# = react_component('Order', props: {order: @order, cart: @cart, cart_items: @cart_items}, prerender: false) %>
<div class="order">
  <div class="refund-page hide-for-print">
    <%= link_to 'Volver a Pedidos', orders_path() %>
    <a href="#" onclick="window.print();return false;">Imprimir Página</a>
    <span><%= link_to 'Reembolso', order_refund_orders_path(@order) %>(<%= @order.refund_orders.count%>)</span>
    <%= link_to 'Editar Forma De Pago', edit_order_path(@order) %>
    <%= link_to 'Borrar Orden', order_path(@order), method: :delete, data: { confirm: 'Estas segura?' } %>


  </div>
    <h1>Orden <%= @order.id %></h1>
    <%= render 'order_details'%>
</div>