config/routes.rb
Rails.application.routes.draw do

  devise_for :users,:controllers => {
    :registrations => "registrations"
  }
  # get 'hello_world', to: 'hello_world#index'

  resources :items
  get 'cart', to: 'items#index'
  get 'inventario', to: 'items#index'
  get 'get_orders_refunded', to: 'orders#get_orders_refunded'
  get 'get_orders_searched', to: 'orders#get_orders_searched'
  get 'get_category_brand', to: 'items#get_category_brand'
  get 'get_items', to: 'items#get_items'
  get 'get_item_orders_refunded', to: 'item_orders#get_item_orders_refunded'


  resources :orders do
    resources :item_orders, only:[:edit, :update]
    resources :custom_items, only:[:edit, :update]
    resources :refund_orders, except:[:destroy] do
      resources :refund_items, except:[:destroy]
    end
  end

  root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_orders, :dependent => :destroy
  has_many :refund_items, through: :item_orders
  has_one_attached :pic
  scope :distinct_brands, -> {select(:brand).distinct}
  scope :get_brand, -> (brand) {where(["brand = ?", "#{brand}"])}
  scope :remove_brand, -> (brand) {where(["brand != ?", "#{brand}"])}

  scope :distinct_categories, -> {select(:category).distinct}
  scope :get_category, -> (category) do
    Rails.cache.fetch("items_#{category}") { where(["category = ?", "#{category}"])}
  end
  scope :remove_category, -> (category) {where(["category != ?", "#{category}"])}

  scope :get_actives, -> do
    Rails.cache.fetch("items_active") do
      puts 'evaluating get_actives...'
      where active: true
    end
  end

  scope :get_inactives, -> do
    Rails.cache.fetch("items_inactive") do
      puts 'evaluating get_inactives...'
      where active: false
    end
  end

  scope :get_ordered_actives, -> do
    Rails.cache.fetch("ordered_active_items") do
      puts 'evaluating get_ordered_actives...'
      get_actives.order(:brand, :thickness, :size, :name)
    end
  end

  scope :get_ordered_inactives, -> do
    Rails.cache.fetch("ordered_inactive_items") do
      puts 'evaluating get_ordered_inactives...'
      get_inactives.order(:brand, :thickness, :size, :name)
    end
  end



  after_commit :flush_cache!

  def update_inventory(quantity)
    self.update(inventory: quantity)
  end

  def set_default_value
    self[:category] ? self[:category] : ""
  end



  def flush_cache!
  puts 'flushing the cache...'
  Rails.cache.delete 'items_active'
  Rails.cache.delete "items_inactive"
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "hello_world"
  skip_before_action :verify_authenticity_token

  def index
    # render :layout => 'hello_world'
    # @items = Item.all
    # @active_items = @items.get_ordered_actives
    # @inactive_items = @items.get_ordered_inactives
    # @categories = @items.distinct_categories
    # @brands = [{brand:"Lanco"}, {brand:"Wilsonart"}, {brand:"Temar"}, {brand:"Hafelle"}, {brand:"Pfister"}, {brand:"Blum"}, {brand:"Sait"}, {brand:"3M"}]
    # @pic_urls = @items.map do |item|
    #   pic_url = ""
    #   pic_url = url_for(item.pic) if item.pic.attached?
    #   { id: item.id, pic_url: pic_url }
    # end
  end # END of index Method


  def show
    @item = Item.find(params[:id])
    if @item.pic.attached?
      respond_to do |format|
        format.html
        format.json {
          render json: {
            pic_url: url_for(@item.pic)
          }
        }
    end
    else
      respond_to do |format|
        format.html
        format.json {
          render json: {
            pic_url: ""
          }
        }
      end
    end
  end

  def new
    @item = Item.new
    @categories = Item.distinct_categories.map{|item| item.category}.sort
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Item.distinct_categories.map{|item| item.category}.sort
  end

  def update
    @item = Item.find(params[:id])
    if params[:inventory]
      @items = Item.all
      @item.update(inventory:params[:inventory])
      render json: {
          active_items: @items.get_ordered_actives,
          inactives_items: @items.get_ordered_inactives
        }
    else
      if @item.update(item_params)
        redirect_to @item
      else
        render 'edit'
      end
    end


  end

  def destroy
    # Item must be converted to CustomItem
    # to be able to refund past purchases

    # Item to be destroyed
    @item = Item.find(params[:id])

    # Item Orders to be destroyed
    items_orders = @item.item_orders

    # passed = true
    if items_orders.count != 0
      items_orders.each do |item_order|
        @custom_item = CustomItem.new(
          name: @item.name,
          quantity: item_order.quantity,
          price_given: item_order.price_given,
          subtotal: item_order.subtotal,
          order_id: item_order.order_id
        )
        @custom_item.refund_items.new(item_order.refund_items.as_json)


        if @custom_item.save
          p "Custom Item Saved ================="
          item_order.refund_items.each { |ri|
            @custom_item.refund_items.create(
              quantity_refunded: ri.quantity_refunded,
              subtotal_refunded: ri.subtotal_refunded,
              refund_order_id: ri.refund_order_id
            )
          }
          p "refunded items ++++++++++++++++++++++"
          @item.destroy
          # p refund_items
          # return passed = false
        end
      end
    end
    # MUST CREATE TEST
    # @item.destroy if passed

    items = Item.all
    return render 'index'
  end

  def get_items
    @items = Item.all
    render json: {
        active_items: @items.get_ordered_actives
        # inactives_items: @items.get_ordered_inactives
      }
  end

  # def get_category_brand
  #   @items = Item.all
  #   column = params[:column]
  #   column_name= params[:columnName]
  #   selected_column_items = []
  #   case column
  #   when 'category'
  #     selected_column_items = column_name!='Todo' ? @items.get_category(column_name) : @items.remove_category("PVC").remove_category("Brazos").remove_category("Superficie").remove_category("Tornillos").remove_category("Tinte").remove_category("Gozne").remove_category("Correderas").remove_category("Routers").remove_category("Tapcon").remove_category("Discos").remove_category("Staples").remove_category("Fregaderos").remove_category("Laminados").remove_brand("Sait").remove_brand("Temar").remove_category("Lazy Susan").remove_category("SeamFil").remove_category("Madera").remove_category("Clavos")
  #   when 'brand'
  #     selected_column_items = @items.get_brand(column_name)
  #   end
  #   respond_to do |format|
  #   format.html
  #   format.json {
  #     render json: {
  #         actives: selected_column_items.get_ordered_actives,
  #         inactives: selected_column_items.get_ordered_inactives
  #       }
  #     }
  #   end
  # end #END of def get_category_brand

  private

  def item_params
    params.require(:item).permit(:active, :name, :category, :brand, :size, :thickness, :color, :sold_price , :bought_price, :pic, :inventory, :stock_number)
  end

end

app/helpers/items_helper.rb
module ItemsHelper

  def display_image(item)
    image_tag(url_for(item.pic)) if item.pic.attached?
  end

end

# <% if @item.pic.attached? %>
#   <image src="<%=url_for(@item.pic)%>" />
# <% end %>

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>

<div class="form-item">
  <p>
    <%= form.label :active %>
    <%= form.radio_button :active, true, :value => true, checked: true %>
    <%= form.label :inactive %>
    <%= form.radio_button :active, false, :value => false%>
  </p>

  <p>
   <%= form.label :Nombre %><br>
   <%= form.text_field :name %>
  </p>

  <p>
   <%= form.label :Categoria %><br>
   <%= form.text_field :category %>
   <%#= select_tag(:category, options_for_select(@categories, @item.set_default_value ), class:"select") %>
  </p>

  <p>
    <%= form.label :Marca %><br>
    <%= form.text_field :brand %>
  </p>

  <p>
    <%= form.label :Tamaño %><br>
    <%= form.text_field :size %>
  </p>

  <p>
    <%= form.label :Grosor %><br>
    <%= form.text_field :thickness %>
  </p>

  <p>
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </p>

  <p>
    <%= form.label :Precio_De_Venta %><br>
    <%= form.text_field :sold_price %>
  </p>

  <p>
    <%= form.label :Precio_De_Compra %><br>
    <%= form.text_field :bought_price %>
  </p>

  <p>
    <%= form.label :Inventario %><br>
    <%= form.text_field :inventory %>
  </p>

  <p>
    <%= form.label :Número_De_Artículo %><br>
    <%= form.text_field :stock_number %>
  </p>


  <p>
   <%= form.submit %>
  </p>
</div>


<% end %>

app/views/items/edit.html.erb
<h1>Editar Elemento</h1>
<%= link_to 'Destroy',  item_path(@item), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= render 'form'%>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= react_component("HelloWorld", props: {current_user: current_user}, prerender:false) %>

app/views/items/new.html.erb
<h1>Crear Nuevo Elemento</h1>
<%= render 'form'%>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="show-item">

<%= link_to "Home", items_path %>

  <p>
   <%= display_image(@item) %>
  </p>

  <p>
    <strong>Activo:</strong>
    <%= @item.active %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= @item.name %>
  </p>

  <p>
    <strong>Categoría:</strong>
    <%= @item.category %>
  </p>

  <p>
    <strong>Marca:</strong>
    <%= @item.brand %>
  </p>

  <p>
    <strong>Tamaño:</strong>
    <%= @item.size %>
  </p>

  <p>
    <strong>Grosor:</strong>
    <%= @item.thickness %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= @item.color %>
  </p>

  <p>
    <strong>Precio De Venta:</strong>
    <%= @item.sold_price %>
  </p>

  <p>
    <strong>Precio De Compra:</strong>
    <%= @item.bought_price %>
  </p>

  <p>
    <strong>Inventario:</strong>
    <%= @item.inventory %>
  </p>

  <p>
    <strong>Número De Artículo:</strong>
    <%= @item.stock_number %>
  </p>
</div>